[project]
name = "tr-webhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "functions-framework>=3.8.2",
    "google-genai>=1.10.0",
    "google-generativeai>=0.8.4",
    "trycourier>=6.2.1",
]
